name: rws_sdk_example
description: Contoh implementasi RWS SDK Flutter (rws_sdk)
publish_to: none

environment:
  sdk: ^3.2.0

dependencies:
  flutter:
    sdk: flutter
  rws_sdk:
    path: ../

flutter:
  uses-material-design: true
