name: rws_example
description: Contoh implementasi RWS SDK Flutter (rws)
publish_to: none

environment:
  sdk: ^3.2.0

dependencies:
  flutter:
    sdk: flutter
  rws:
    path: ../

flutter:
  uses-material-design: true
